### ISSUE TITLE
fix(docs): move initialization js from jinja2 template to site.js

### ISSUE THREAD

**Issue by danceratopz** [ethereum/execution-spec-tests#813]
Currently, the datatable behaviour in the test function parameter overview tables are customized directly in the jinja2 template (i.e., in the each site page separately). It would be cleaner to have this in `docs/javascripts/site.js`.

While I could get mkdocs to take the config from `site.js` (e.g, scrollX, e.g.) was available, it only worked upon hard reload, not upon navigating from page to page. The table was available but no styling was applied.

Tried messing about with `site.js` and various delays, but 

mkdocs.yml:
```yaml
extra_javascript:
  - https://code.jquery.com/jquery-3.5.1.js
  - https://cdn.datatables.net/1.10.21/js/jquery.dataTables.js
  - javascripts/site.js

extra_css:
  - https://cdn.datatables.net/1.10.21/css/jquery.dataTables.css
```

site.js (we should use a better selector)
```js
$(document).ready(function () {
    $('#test_table').DataTable({
        pageLength: -1,
        scrollX: true,
        autoWidth: false
    });
});
```
